apiVersion: v1
kind: Service
metadata:
  name: platformnpservice-srv
spec:
  type: NodePort
  selector:
    app: platformservice
  ports:
    - name: platformservice
      protocol: TCP
      port: 80
      targetPort: 80
# kubectl apply -f platforms-np-srv.yaml
# kubectl get services -o wide
# kubectl delete service platformnpservice-srv
# http://localhost:[service-port]/api/Platforms
# http://localhost:31555/api/Platforms
